### ISSUE TITLE
{"Exception":"BAD END POINT"}

### ISSUE THREAD

**Issue by mikael-andre** [CiscoDevNet/webex-contact-center-dbconnector#5]
Hi,

When I try to request my endpoint directly, I have this message:
{"Exception":"BAD END POINT"}

But, inside my connector, I have this one:
SUCCESS
Endpoint authentication is active:false
Request:
https://fqdn_connector/rest/webexcc/71eb22fe-402b-4c09-9f01-40743fee4926?userid=145
Response:
{"ticket_count":"1"}
SQL:
SELECT COUNT(*) AS ticket_count FROM tjg30_ats_tickets

**Comment by jiwyatt** [comment]
Error Message :
{"Exception":"BAD END POINT"}

Summary of the issue:
The API server is not able to load the connector endpoint(s) from the Connector.obj file.

Solution:
Out of the box, all endpoints will get loaded from a file called data/Connector.obj.

The location of where this file is persisted is defined in the application.yml file.
You can choose to persist files on AWS bucket or localhost.

Check to see if all of the files from the data directory have read/write access.
If you are developing from localhost and publishing to domain fqdn_connector, make sure you copy over data directory to domain fqdn_connector.


Doc reference:
https://github.com/CiscoDevNet/webex-contact-center-dbconnector/blob/main/webexcc-dbconnector-springboot/webexcc-dbconnector-springboot.md


Jim

From: Mikaël ANDRE ***@***.***>
Date: Tuesday, April 4, 2023 at 3:19 AM
To: CiscoDevNet/webex-contact-center-dbconnector ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CiscoDevNet/webex-contact-center-dbconnector] {"Exception":"BAD END POINT"} (Issue #5)

Hi,

When I try to request my endpoint directly, I have this message:
{"Exception":"BAD END POINT"}

But, inside my connector, I have this one:
SUCCESS
Endpoint authentication is active:false
Request:
https://fqdn_connector/rest/webexcc/71eb22fe-402b-4c09-9f01-40743fee4926?userid=145
Response:
{"ticket_count":"1"}
SQL:
SELECT COUNT(*) AS ticket_count FROM tjg30_ats_tickets

**Comment by mikael-andre** [comment]
Hi Jim,

You solved my problem, it was a read/write access problem on *.obj files.

Thank you.
